financr:
    client_id: 5cb67695f9c7ee0012d5ade1
    secret: b9cc44fc9bf078cfe16bd487064db5
    public_key: 707b8de9c0ab02c65ef8476471e5d9
    plaid_products: transactions
    plaid_env: sandbox


insults:

    people:
        - "your mom"
        - "your friends"
        - "a girl named Brandy"
        - "shady pete"

    yothang:
        - "your face"
        - "you"
        - "your soul"
        - "your smell"

    pet:
        - "a gerbal"
        - "a cat"
        - "an anteater"

    templates:
        - "ya <people> wont like <yothang> any better when you spend money on <cat>"
        - "last night your mom told me to tell you to stop spending money on <cat>"
        - "<cat> really? <pet> would love you more"
        - "spent a lot of money on UGLY <cat>"
        - "congrats, you made <payee> richer. all you got was guilt... and debt"
        - "buying <cat> wont get you laid, crawling up a chickens butt just might"
        - "<cat>?!?! burning a whole in your wallet faster than Notre Dame I see"
        - "hey everybody. look at me. i spent even MORE on <cat>"
        - "Your mother was a hamster, and your father smelt of elderberries. also, dont buy <cat>"

    foodTemplates:
        - "<cat>?!?! Hey you have something on your chin… no the third one down."
        - "more <cat>? You're the reason they invented double doors!"
        - "we already got you your own zip code. NO MORE <cat>"


trans:
    payee:
        - "Google"
        - "Amazon"
        - "Smiths Marketplace"
        - "Wal★Mart"
        - "Target"
        - "The Feds"
        - "Russian Spy"
        - "Shady Petes girlfriend"
        - "Shady Pete your local drug dealer"
        - "Utah Liquor Store"


    category:
        - "drugs"
        - "Water"
        - "Transportation Centers"
        - "Nutritionists"
        - "Business Services"
        - "Swimming Pool Maintenance and Services"
        - "News Reporting"
        - "Hair Removal"
        - "Mental Health"
        - "Post Offices"
        - "Beaches"
        - "Turkish"
        - "Carpenters"
        - "Tourist Information and Services"
        - "Kids' Store"
        - "Vegan and Vegetarian"
        - "Bakery"
        - "Housewares"
        - "Home Inspection Services"
        - "Pathologists"
        - "Coinbase"
        - "Costumes"
        - "Lodges and Vacation Rentals"
        - "Fraud Dispute"
        - "Gift and Novelty"
        - "Music and Show Venues"
        - "Real Estate"
        - "Fish and Chips"
        - "Alternative Medicine"
        - "Transfer"
        - "Heating, Ventilating, and Air Conditioning"
        - "Charter Buses"
        - "Miniature Golf"
        - "Advertising Agencies and Media Buyers"
        - "Apparel and Fabric Products"
        - "Dance and Music"
        - "Movers"
        - "Cards and Stationery"
        - "Swimwear"
        - "Bank Fees"
        - "Racquetball"
        - "French"
        - "Check Cashing"
        - "Hotel Lounge"
        - "Indonesian"
        - "Natural Parks"
        - "Senior Citizen Services"
        - "Landscaping and Gardeners"
        - "Arts and Entertainment"
        - "Cycling"
        - "ACH"
        - "Parking"
        - "Gastroenterologists"
        - "Betterment"
        - "Transportation Equipment"
        - "Equestrian"
        - "Strip Club"
        - "Plastic Products"
        - "Dance"
        - "Landmarks"
        - "Hair Salons and Barbers"
        - "Sports and Recreation Camps"
        - "Industrial Machinery and Equipment"
        - "Online Advertising"
        - "Gastropub"
        - "Funeral Services"
        - "Resorts"
        - "Public Relations"
        - "Food and Beverage"
        - "Glasses and Optometrist"
        - "Optometrists"
        - "Towing"
        - "Wire"
        - "Market Research and Consulting"
        - "Veterinarians"
        - "Arts and Crafts"
        - "Leather Goods"
        - "Accessories Store"
        - "Bed and Breakfasts"
        - "Cajun"
        - "Swimming"
        - "Collections"
        - "Livestock and Animals"
        - "Computers and Electronics"
        - "Arcades and Amusement Parks"
        - "Computers and Office Machines"
        - "Golf"
        - "Contractors"
        - "Financial"
        - "Marine Supplies"
        - "Psychologists"
        - "Plastic Surgeons"
        - "Racquet Sports"
        - "Promotional Items"
        - "Burrito"
        - "Carpet and Flooring"
        - "Storage"
        - "Renewable Energy"
        - "Shipping and Freight"
        - "Breweries"
        - "Neurologists"
        - "Computers"
        - "Massage Clinics and Therapists"
        - "Women's Store"
        - "Sports Bar"
        - "Courts"
        - "Overdraft"
        - "Wire Transfer"
        - "Boating"
        - "Interest Earned"
        - "Business Brokers and Franchises"
        - "Non-Metallic Minerals"
        - "Internet Cafes"
        - "Music, Video and DVD"
        - "Tanning Salons"
        - "Children"
        - "Youth Organizations"
        - "Shops"
        - "Food and Drink"
        - "PayPal"
        - "Mexican"
        - "Athletic Fields"
        - "Accounting and Bookkeeping"
        - "Football"
        - "Restaurants"
        - "Hiking"
        - "Pizza"
        - "Pediatricians"
        - "Forestry"
        - "Lakes"
        - "Indian"
        - "Psychics and Astrologers"
        - "Catering"
        - "Community"
        - "Jazz and Blues Cafe"
        - "Coffee Shop"
        - "Forests"
        - "Drug and Alcohol Services"
        - "Personal Trainers"
        - "Blood Banks and Centers"
        - "RVs and Motor Homes"
        - "Stock Brokers"
        - "Mining"
        - "Hospitals, Clinics and Medical Centers"
        - "Aquarium"
        - "Latin American"
        - "Fire Stations"
        - "Construction Supplies"
        - "Law Enforcement"
        - "Property Management"
        - "Art Dealers and Galleries"
        - "Casinos and Gaming"
        - "Campgrounds and RV Parks"
        - "Recreation Centers"
        - "ATMs"
        - "Gyms and Fitness Centers"
        - "Square"
        - "Japanese"
        - "Petroleum"
        - "Loan"
        - "Baseball"
        - "Recreation"
        - "Home Improvement"
        - "Distillery"
        - "Distribution"
        - "Bicycles"
        - "Buildings and Structures"
        - "Plaid"
        - "Heliports"
        - "Car Parts and Accessories"
        - "Parks"
        - "Urologists"
        - "Race Tracks"
        - "American"
        - "Hostels"
        - "Payroll"
        - "Gun Ranges"
        - "Paintball"
        - "Newsstands"
        - "Student Aid and Grants"
        - "Outlet"
        - "Beauty Products"
        - "Medical Supplies and Labs"
        - "Holding and Investment Offices"
        - "Hot Air Balloons"
        - "Furniture and Fixtures"
        - "Office Supplies"
        - "Withdrawal"
        - "Warehouses and Wholesale Stores"
        - "Florists"
        - "Snow Sports"
        - "Cardiologists"
        - "Vintage and Thrift"
        - "Mosques"
        - "Events and Event Planning"
        - "Rock Climbing"
        - "Hunting and Fishing"
        - "Temple"
        - "Insurance"
        - "Symphony and Opera"
        - "Caribbean"
        - "Boat"
        - "Banking and Finance"
        - "Welding"
        - "Fund Raising"
        - "Seafood"
        - "Internet Services"
        - "Venmo"
        - "Obstetricians and Gynecologists"
        - "Wood Products"
        - "Airlines and Aviation Services"
        - "Tree Service"
        - "Car Dealers and Leasing"
        - "Dwolla"
        - "Kitchens"
        - "Night Clubs"
        - "Education"
        - "Web Design and Development"
        - "Coal"
        - "Boutique"
        - "Disabled Persons Services"
        - "Libraries"
        - "Pools and Spas"
        - "Thai"
        - "Barbecue"
        - "Skating"
        - "Corporate Housing"
        - "Deposit"
        - "Cafe"
        - "Emergency Services"
        - "Dance Halls and Saloons"
        - "Salvage Yards"
        - "Fraternities and Sororities"
        - "Hardware Store"
        - "Pharmacies"
        - "Laundry and Garment Services"
        - "Payment"
        - "Auto Transmission"
        - "Water Sports"
        - "Taxes"
        - "Art and Graphic Design"
        - "Bookstores"
        - "Delis"
        - "Packaging"
        - "Acupuncture"
        - "Piercing"
        - "Cottages and Cabins"
        - "Police Stations"
        - "Doors and Windows"
        - "Luggage"
        - "Men's Store"
        - "Car and Truck Rentals"
        - "Save As You Go"
        - "Automation and Control Systems"
        - "Mountains"
        - "Geological"
        - "Import and Export"
        - "Insufficient Funds"
        - "Crop Production"
        - "Telecommunication Services"
        - "Cuban"
        - "Go Carts"
        - "Manufacturing"
        - "Monuments and Memorials"
        - "Tennis"
        - "Machine Shops"
        - "Car Service"
        - "Hockey"
        - "Culinary Lessons and Schools"
        - "Organizations and Associations"
        - "Podiatrists"
        - "Rivers"
        - "Creative Services"
        - "Family Medicine"
        - "Painting"
        - "Mediterranean"
        - "Chemicals and Gasses"
        - "Lingerie Store"
        - "Religious"
        - "Public and Social Services"
        - "Paper"
        - "Furniture and Home Decor"
        - "Interior Design"
        - "Limos and Chauffeurs"
        - "Internal Account Transfer"
        - "Loans and Mortgages"
        - "Entertainment"
        - "Electrical Equipment and Components"
        - "Hotels and Motels"
        - "Equipment Rental"
        - "Day Care and Preschools"
        - "Excess Activity"
        - "Nightlife"
        - "Credit Card"
        - "Department Stores"
        - "Mobile Homes"
        - "Taxi"
        - "Brazilian"
        - "Repair Services"
        - "Hookah Lounges"
        - "Social Clubs"
        - "Writing, Copywriting and Technical Writing"
        - "Tutoring and Educational Services"
        - "Construction"
        - "Flea Markets"
        - "Internal Medicine"
        - "Afghan"
        - "Vocational Schools"
        - "Employment Agencies"
        - "Financial Planning and Investments"
        - "Fairgrounds and Rodeos"
        - "Primary and Secondary Schools"
        - "Wine Bar"
        - "Refund"
        - "Food and Beverage Store"
        - "Business and Strategy Consulting"
        - "Running"
        - "Cameras"
        - "Sushi"
        - "Water and Waste Management"
        - "Winery"
        - "Heating, Ventilating and Air Conditioning"
        - "Dating and Escort"
        - "Personal Care"
        - "Building and Land Surveyors"
        - "Cash Advance"
        - "Leather"
        - "Health Food"
        - "Musical Instruments"
        - "Ear, Nose and Throat"
        - "Supermarkets and Groceries"
        - "Motorcycle, Moped and Scooter Repair"
        - "Infrastructure"
        - "Hardware and Services"
        - "Diners"
        - "Adult"
        - "Auctions"
        - "Boarding Houses"
        - "Correctional Institutions"
        - "Military"
        - "Gymnastics"
        - "Government Departments and Agencies"
        - "Digital Purchase"
        - "Soccer"
        - "Boat Dealers"
        - "Wedding and Bridal"
        - "Credit Reporting"
        - "Fences, Fireplaces and Garage Doors"
        - "Billiards and Pool"
        - "Respiratory"
        - "Human Resources"
        - "Travel Agents and Tour Operators"
        - "Manicures and Pedicures"
        - "Photography"
        - "Services"
        - "Upholstery"
        - "Sports Clubs"
        - "ATM"
        - "Plastics"
        - "Rafting"
        - "Pawn Shops"
        - "Service Instruments"
        - "Car Appraisers"
        - "Agriculture and Forestry"
        - "Ice Cream"
        - "Metal Products"
        - "Print, TV, Radio and Outdoor Advertising"
        - "Heating, Ventilation and Air Conditioning"
        - "Roofers"
        - "Motorcycles, Mopeds and Scooters"
        - "Skin Care"
        - "Discount Stores"
        - "Scientific"
        - "Metal"
        - "Benefits"
        - "Chase QuickPay"
        - "Interest"
        - "Audiovisual"
        - "Portuguese"
        - "Video Games"
        - "Lawn and Garden"
        - "Plumbing"
        - "Combat Sports"
        - "Household"
        - "Karaoke"
        - "Eastern European"
        - "Airports"
        - "Late Payment"
        - "Specialty"
        - "Industrial Machinery and Vehicles"
        - "Breakfast Spot"
        - "Playgrounds"
        - "Electrical Equipment"
        - "Sanitary and Waste Management"
        - "Immigration"
        - "Gas"
        - "Acorns"
        - "Square Cash"
        - "Oil and Gas"
        - "Chiropractors"
        - "Oncologists"
        - "Italian"
        - "Caretakers"
        - "Steakhouses"
        - "Physicians"
        - "Transportation"
        - "Legal"
        - "Real Estate Agents"
        - "Synagogues"
        - "Cupcake Shop"
        - "Basketball"
        - "Picnic Areas"
        - "Printing and Publishing"
        - "Pregnancy and Sexual Health"
        - "Car Wash and Detail"
        - "Toys"
        - "Middle Eastern"
        - "Nurses"
        - "Driving Schools"
        - "Healthcare Services"
        - "Digit"
        - "Industrial Supplies"
        - "Interest Charged"
        - "Assisted Living Services"
        - "Beer, Wine and Spirits"
        - "Travel"
        - "Batting Cages"
        - "Party Centers"
        - "Security and Safety"
        - "Third Party"
        - "Greek"
        - "Wholesale"
        - "Public Transportation Services"
        - "Nonmetallic Mineral Products"
        - "Auto Oil and Lube"
        - "Photos and Frames"
        - "Burgers"
        - "Check"
        - "Mobile Phones"
        - "Circuses and Carnivals"
        - "Dessert"
        - "Asian"
        - "Automotive"
        - "Tattooing"
        - "Home Appliances"
        - "Used Car Dealers"
        - "Anesthesiologists"
        - "Colleges and Universities"
        - "Logging and Sawmills"
        - "Dermatologists"
        - "Shoe Store"
        - "Subscription"
        - "Advertising and Marketing"
        - "Debit"
        - "Government Lobbyists"
        - "Sports Venues"
        - "Art School"
        - "Bowling"
        - "Churches"
        - "Sporting Goods"
        - "Apartments, Condos and Houses"
        - "Skydiving"
        - "Tobacco"
        - "Dentists"
        - "Architects"
        - "Commercial Real Estate"
        - "Metals"
        - "Spas"
        - "Tolls and Fees"
        - "German"
        - "Outdoors"
        - "Research"
        - "Swiss"
        - "General Surgery"
        - "Animal Shelter"
        - "Search Engine Marketing and Optimization"
        - "Filipino"
        - "Software Development"
        - "Charities and Non-Profits"
        - "Psychiatrists"
        - "Scandinavian"
        - "Rubber"
        - "Antiques"
        - "Convenience Stores"
        - "Retirement"
        - "Maintenance and Repair"
        - "Falafel"
        - "Fuel Dealer"
        - "Canoes and Kayaks"
        - "Theatrical Productions"
        - "Radiologists"
        - "Korean"
        - "Gardens"
        - "Masonry"
        - "Stadiums and Arenas"
        - "Auto Tires"
        - "Pets"
        - "Orthopedic Surgeons"
        - "Cruises"
        - "Australian"
        - "Physical Therapy"
        - "Ride Share"
        - "Chinese"
        - "Healthcare"
        - "Yoga and Pilates"
        - "Rent"
        - "Real Estate Appraiser"
        - "Pest Control"
        - "Lighting Fixtures"
        - "Gas Stations"
        - "Scuba Diving"
        - "Rubber Products"
        - "Bagel Shop"
        - "Tax"
        - "Tailors"
        - "Classic and Antique Car"
        - "Billpay"
        - "Utilities"
        - "Rail"
        - "Paper Products"
        - "Spanish"
        - "Cemetery"
        - "Adult Education"
        - "Foreign Transaction"
        - "Adult Entertainment"
        - "Counseling and Therapy"
        - "Environmental"
        - "Dance Schools"
        - "Media"
        - "Keep the Change Savings Program"
        - "Historic Sites"
        - "Credit Counseling and Bankruptcy Services"
        - "Glass Products"
        - "Media Production"
        - "Refrigeration and Ice"
        - "Facilities and Nursing Homes"
        - "Electricians"
        - "Shopping Centers and Malls"
        - "Ethiopian"
        - "Zoo"
        - "Juice Bar"
        - "Cable"
        - "Hobby and Collectibles"
        - "Auto Smog Check"
        - "Lodging"
        - "Computer Training"
        - "Textiles"
        - "Housing Assistance and Shelters"
        - "Engineering"
        - "Ophthalmologists"
        - "Farmers Markets"
        - "Credit"
        - "Bus Stations"
        - "Art Restoration"
        - "Clothing and Accessories"
        - "Food Truck"
        - "Movie Theatres"
        - "Donuts"
        - "Electric"
        - "Fast Food"
        - "Service"
        - "Museums"
        - "Cleaning"
        - "Management"
        - "Real Estate Development and Title Companies"
        - "Jewelry and Watches"
        - "Moroccan"
        - "African"
        - "Bar"
        - "Direct Mail and Email Marketing Services"

